FROM node:20-slim AS build
WORKDIR /app

ARG VITE_GOOGLE_CLIENT_ID
ARG VITE_GEMINI_API_KEY
ARG VITE_ALL_FEATURES
ARG VITE_AI_API_BASE
ENV VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
ENV VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
ENV VITE_ALL_FEATURES=${VITE_ALL_FEATURES}
ENV VITE_AI_API_BASE=${VITE_AI_API_BASE}

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build && npm prune --omit=dev

FROM node:20-slim
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=8080

COPY --from=build /app ./

EXPOSE 8080
CMD ["node", "server/index.mjs"]
